---
pipeline:
  test:
    image: python:3.7-alpine3.10
    commands:
      - apk add --no-cache bash git python-dev gcc musl-dev postgresql-dev libffi-dev libressl-dev
      - pip install --upgrade pip
      - pip install -r requirements/ci.txt --no-cache-dir
      - ./tcp-port-wait.sh postgres 5432
      - flake8
      - pytest --cache-clear
    when:
      event:
      - pull_request
      - push
      - tag
    environment:
      ALLOWED_HOSTS: "*"
      API_URL: /api/docs
      CORS_ORIGIN_WHITELIST: "*"
      DATABASE_ENGINE: "postgresql"
      DATABASE_NAME: "bifrost_api"
      DATABASE_USER: "root"
      DATABASE_PASSWORD: "root"
      DATABASE_HOST: "postgres"
      DATABASE_PORT: "5432"
      DEFAULT_ORG: "Default Organization"
      DJANGO_SETTINGS_MODULE: "bifrost-api.settings.production"
      SOCIAL_AUTH_GITHUB_REDIRECT_URL: "/complete/github"
      SOCIAL_AUTH_GOOGLE_OAUTH2_REDIRECT_URL: "/complete/google-oauth2"
      SOCIAL_AUTH_MICROSOFT_GRAPH_REDIRECT_URL: "/complete/microsoft-graph"
      JWT_ISSUER: "bifrost"
      JWT_PRIVATE_KEY_RSA_BIFROST: |-
        -----BEGIN RSA PRIVATE KEY-----
        MIIBOgIBAAJBAMtUe741n497BS4syFvey617qA+b4DQSyHj4xE0ZH5qRuk/A42i5
        zUJidSkFs1Wvq9ShOamST1vrmHriBrYYu7MCAwEAAQJBAI2hUXiSvYwh8t/RDdcA
        f/tdkRkeSLO9CatKDOJvR5ZQAL5+7iNHTMGOC2FCU3WKSdlEo/xW3kD6omYbIWPk
        hXECIQD58w4Zl3FSaoWBhBmmyJF08cOQP2Z8amewd70LV0LNlQIhANBAhrTxnDG2
        KprAffkxjcrV/6ZWC5kGqckTNUUhf0InAiBbosNpmH8gYxM9L4wj/GZvhG9ZRBUz
        yeLn7I4vSTehnQIgJEaZMHvF0YMB+OL/DqFrKaINXlQuwQFAIh6OcPRczpECICpM
        q/qlwzGMpOD6blcWDUqgS6HXpS73To/F8RE56FP+
        -----END RSA PRIVATE KEY-----
      JWT_PUBLIC_KEY_RSA_BIFROST: |-
        -----BEGIN PUBLIC KEY-----
        MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBALFc9NFZaOaSwUMPNektbtJqEjYZ6IRB
        qhqvJu1hKPYn9HYd75c0gIDYHJ9lb7QwQvg44aO27104rDK0xSstzL0CAwEAAQ==
        -----END PUBLIC KEY-----"""
      SECRET_KEY: "nothing"
      SOCIAL_AUTH_CLIENT_ID: "vBn4KsOCthm7TWzMH0kVV0dXkUPJEtOQwaLu0eoC"
      SOCIAL_AUTH_CLIENT_SECRET: |-
        0aYDOHUNAxK4MjbnYOHhfrKx8Ezj3jd7aKq2C7yRDZ6FbAL4SgRFxY8N6GbB6IGyC
        gpT6pmQ5pEVJmH7mIEUJxyXKbta7ebxULLULjXwnJYGhUgT2hPyCfptkWFhsZVV

  build-docker-image-tag:
    image: plugins/docker
    registry:
      from_secret: DOCKER_REGISTRY
    repo:
      from_secret: DOCKER_REPO
    username:
      from_secret: DOCKER_USERNAME
    password:
      from_secret: DOCKER_PASSWORD
    auto_tag: true
    insecure: true
    file: Dockerfile
    when:
      event:
      - tag
      status:
      - success

  deploy-docs:
    image: python:3.7
    commands:
      - pip install -r requirements/base.txt --no-cache-dir
      - python manage.py generate_swagger > swagger.json
      - eval "$(ssh-agent -s)"
      - mkdir -p /root/.ssh
      - echo "$${SSH_KEY}\n" > /root/.ssh/id_rsa
      - echo "$${SSH_PUBLIC_KEY}\n" > /root/.ssh/id_rsa.pub
      - ssh-keyscan -t rsa github.com >> /root/.ssh/known_hosts
      - chmod 600 /root/.ssh/id_rsa*
      - ssh-add -k /root/.ssh/id_rsa
      - git config --global user.email "engine@humanitec.com"
      - git config --global user.name "HumanitecBot"
      - git clone git@github.com:Humanitec/docs-site.git
      - mkdir -p docs-site/hugo/content/bifrost/
      - mkdir -p docs-site/api/bifrost/
      - cd docs-site/hugo/content/bifrost/
      - cp ../../../../docs/_index.md .
      - cd ../../../api/bifrost
      - cp ../../../swagger.json .
      - cd ../
      - git add .
      - git diff-index --quiet HEAD || git commit -m "Updated documentation for BiFrost"
      - git push origin master
    environment:
      DATABASE_ENGINE: "postgresql"
      DATABASE_NAME: "bifrost_api"
      DATABASE_USER: "root"
      DATABASE_PASSWORD: "root"
      DATABASE_HOST: "postgres"
      DATABASE_PORT: "5432"
      DJANGO_SETTINGS_MODULE: "bifrost-api.settings.base"
      SECRET_KEY: "nothing"
    secrets:
    - SSH_KEY
    - SSH_PUBLIC_KEY
    when:
      event:
      - tag
      status:
      - success

  notify-slack:
    image: plugins/slack
    channel: drone-ci
    username: Drone-CI
    secrets: [SLACK_WEBHOOK]
    when:
      event:
      - push
      - tag
      branch:
      - master
      status:
      - failure

services:
  postgres:
    image: postgres:9.6
    environment:
      - POSTGRES_DB=bifrost_api
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
